language: node_js
node_js:
  - node
  - 12
  - 10
cache: npm
install:
  - npm install
script:
  - npm run test
jobs:
  include:
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release